version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.16.1
    working_directory: ~/qa-test
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          keys:
            - dependency-cache-{{checksum "package-lock.json"}}
            - dependency-cache
      - run:
          name: Install npm dependencies
          command: npm install
      - run:
          name: run test
          command: npm run test
      - run:
          name: Parcel build
          command: npm run build
      - save_cache:
          key: dependency-cache-{{checksum "package-lock.json"}}
          paths:
            - ./node_modules
      - store_artifacts:
          path: dist/
      - save_cache:
          key: distribution-{{.BuildNum}}
          paths:
            - dist/
  deploy:
    machine:
      enabled: true
    working_directory: ~/qa-test
    steps:
      - restore_cache:
          keys:
            - distribution-{{.BuildNum}}
            - distribution
      - add_ssh_keys:
          fingerprints:
            "e4:47:d5:15:58:e3:cb:1a:2b:17:9e:02:10:bb:37:47"
      - run:
          name: Clean up previous build
          command: ssh root@51.91.96.87 -p 9050 'rm -rf /var/www/html/*'
      - run:
          name: Deploy using SCP
          command: scp -P 9050 -r ~/qa-test/dist/* "root@51.91.96.87:/var/www/html/"
workflows:
  build-and-deploy:
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - hold
