version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.16.1
    working_directory: ~/qa-test
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          keys:
            - dependency-cache-{{checksum "package-lock.json"}}
            - dependency-cache
      - run:
          name: Install npm dependencies
          command: npm install
      - run:
          name: run test
          command: npm run test
      - run:
          name: Parcel build
          command: npm run build
      - save_cache:
          key: dependency-cache-{{checksum "package-lock.json"}}
          paths:
            - ./node_modules
      - store_artifacts:
          path: dist/
      - save_cache:
          key: distribution-{{.BuildNum}}
          paths:
            - dist/
workflows:
  node-tests:
    jobs:
      - build
